### ISSUE TITLE
Consider renaming repo "java-next"

### ISSUE THREAD

**Issue by fwgreen** [forax/valuetype-lambda#1]
Thank you for providing these builds.  It isn't easy for us novice users to try out experimental features.  

PS
If I encounter any odd behaviors, is `amber-dev` the correct place to report them?

**Comment by forax** [comment]
repo renamed !
amber-dev is the place to report bugs found using the jdk-12-amber, for jdk-12-loom, it's loom-dev and for jdk-12-lword, it's valhalla-dev
